modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/ItsBlackGear/Platform/issues"

[[mods]]
   modId="platform"
   version="${version}"
   displayName="Platform"

   logoFile="icon.png"

   authors = "ItsBlackGear"
   description="Library mod that aims to ease up the development of mods based on Forge and Fabric"

[[dependencies.platform]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.platform]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
