modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/ItsBlackGear/Platform/issues"

[[mods]]
   modId="platform"
   version="${version}"
   displayName="Platform"

   logoFile="icon.png"

   authors = "ItsBlackGear"
   description="Cross-Platform library mod based on Architectury to access both Forge and Fabric APIs"

[[dependencies.platform]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.platform]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,)"
   ordering="NONE"
   side="BOTH"
