modLoader="javafml"
license="LGPLv3"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/ItsBlackGear/Platform/issues"

[[mods]]
   modId = "platform"
   version = "1.2.7"
   displayName = "Platform"
   displayURL = "https://github.com/ItsBlackGear/Platform"
   authors = "ItsBlackGear"
   description = "Cross-Platform library mod based on Architectury to access both Forge and Fabric APIs"
   logoFile = "icon.png"

[[dependencies.platform]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.platform]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,)"
   ordering="NONE"
   side="BOTH"